import type { Metadata } from "next";
import { Roboto, Work_Sans } from "next/font/google";
import "./media/global.css";
import "@/app/media/widget2.css";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"],
    variable: "--sans", //css ref
    display: "swap",
});
// const workSans = Work_Sans({
//     subsets: ["latin"],
//     weight: ["400", "500", "700"],
//     display: "swap",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.className}`}>{children}</body>
        </html>
    );
}
